#!/bin/bash
sudo ./system_backup.sh

sudo cp -rf /boot/config.txt ./boot/config-nomal.txt

sudo cp -rf ./boot/config-nomal.txt ./boot/config.txt.bak
sudo echo "hdmi_force_hotplug=1" >> ./boot/config.txt.bak
sudo cp -rf ./boot/config.txt.bak /boot/config.txt

sudo sync
sudo sync

read -r -p "Reboot is required, are you sure? " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]
then
    sudo reboot
else
    echo "Restart manually to apply the changes."
fi