#!/bin/bash

sudo ./system_backup.sh

source ./system_config.sh
#sudo cp -rf ./boot/config-nomal.txt ./boot/config.txt.bak
sudo echo "hdmi_force_hotplug=1" >> ./boot/config.txt.bak
sudo cp -rf ./boot/config.txt.bak /boot/config.txt

sudo sync
sudo sync

echo "reboot now"
sudo reboot
